version: 2.1
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.12-bionic
    working_directory: /work
    steps:
      - checkout
      - run: make -f topolvm-node/Makefile SUDO="" setup
      - run: make test
  test_lvmd:
    machine: true
    working_directory: /home/circleci/work
    steps:
      - checkout
      - run:
          name: install lvm
          command: |
            sudo apt-get update
            sudo apt-get -y install --no-install-recommends lvm2
      - run:
          name: setup golang
          command: |
            sudo rm -rf /usr/local/go
            GO_VERSION=1.12.5
            curl -fsSL -o go${GO_VERSION}.linux-amd64.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - run:
          name: run test
          command: sudo env "GO111MODULE=on" "CIRCLECI=${CIRCLECI}" "CIRCLECI_EXECUTOR=machine" /usr/local/go/bin/go test -mod=vendor -race -v ./lvmd
  micro_test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /home/circleci/work
    steps:
      - checkout
      - run:
          name: setup golang
          command: |
            sudo rm -rf /usr/local/go
            GO_VERSION=1.12.5
            curl -fsSL -o go${GO_VERSION}.linux-amd64.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - run:
          name: Install microk8s
          command: |
            cd microtest
            make CONTAINER_BUILDER=docker setup
      - run:
          name: Watch apiserver
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_service snap.microk8s.daemon-apiserver
          background: true
      - run:
          name: Watch scheduler
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_service snap.microk8s.daemon-scheduler
          background: true
      - run:
          name: Watch controller-manager
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_service snap.microk8s.daemon-controller-manager
          background: true
      - run:
          name: Watch kubelet
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_service snap.microk8s.daemon-kubelet
          background: true
      - run:
          name: Watch topolvm-node topolvm-node container
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_pod kube-system app.kubernetes.io/name=csi-topolvm-node topolvm-node
          background: true
      - run:
          name: Watch topolvm-node node container
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_pod kube-system app.kubernetes.io/name=csi-topolvm-node node
          background: true
      - run:
          name: Watch csi-topolvm-controller controller container
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_pod kube-system app.kubernetes.io/name=csi-topolvm-controller controller
          background: true
      - run:
          name: Run test
          command: |
            cd microtest
            make start-lvmd
            make GINKGO=/home/circleci/.go_workspace/bin/ginkgo CONTAINER_BUILDER=docker test
          environment:
            CIRCLECI_EXECUTOR: machine

workflows:
  version: 2
  main:
    jobs:
      - build
      - test_lvmd
      - micro_test
