---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-topolvm-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-topolvm-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-topolvm-controller
    spec:
      containers:
        - name: controller
          image: topolvm:latest
          imagePullPolicy: Never
          command:
            - /csi-topolvm
            - --socket=/tmp/lvmd.sock
