---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-topolvm-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-topolvm-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-topolvm-controller
    spec:
      containers:
        - name: controller
          image: topolvm:latest
          imagePullPolicy: Never
          command:
            - /csi-topolvm
            - controller
            - --socket-name=/run/topolvm/csi-topolvm.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm

        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.1.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=/run/topolvm/csi-topolvm.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm
      volumes:
        - name: socket-dir
          emptyDir: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-topolvm-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-topolvm-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-topolvm-node
    spec:
      containers:
        - name: node
          image: topolvm:latest
          imagePullPolicy: Never
          command:
            - /csi-topolvm
            - node
            - --node-name=test-node
            - --socket-name=/run/topolvm/csi-topolvm.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm

        - name: csi-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=/run/topolvm/csi-topolvm.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/<drivername.example.com>/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm
      volumes:
        - name: socket-dir
          emptyDir: {}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm
provisioner: csi-topolvm.cybozu-ne.co
volumeBindingMode: WaitForFirstConsumer

