apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: topolvm-hook
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-hook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-hook
    spec:
      containers:
        - name: topolvm-hook
          image: lvmetrics:latest
          imagePullPolicy: Never
          command:
            - /topolvm-hook
            - --listen=:9252
            - --cert=/certs/server.pem
            - --key=/certs/server-key.pem
          volumeMounts:
            - name: server-certs
              mountPath: /certs
      hostNetwork: true
      volumes:
        - name: server-certs
          secret:
            secretName: topolvm-hook-certs  
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: topolvm-hook
  labels:
    app.kubernetes.io/name: topolvm-hook
webhooks:
  - name: topolvm-hook.cybozu-ne.co
    clientConfig:
      url: https://localhost:9252/mutate
      caBundle: "MIIDYDCCAkigAwIBAgIUad+UJGMY5nfSPaBoCUZmLTYBIBEwDQYJKoZIhvcNAQELBQAwSDELMAkGA1UEBhMCSlAxETAPBgNVBAgTCENodW9oLWt1MQ4wDAYDVQQHEwVUb2t5bzEWMBQGA1UEAxMNY2x1c3Rlci5sb2NhbDAeFw0xOTA1MjEwMTU2MDBaFw0yNDA1MTkwMTU2MDBaMEgxCzAJBgNVBAYTAkpQMREwDwYDVQQIEwhDaHVvaC1rdTEOMAwGA1UEBxMFVG9reW8xFjAUBgNVBAMTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDWzA041qq0+RcgyugyJmMxaXuI+PgnJ1TOQL9yhhcZTYLbQ24lUXIB/ebJ2o9aB5IF3iIxniYHfDnRlOsMPIX4SqtAzFRkf8+YVBhUfsSnqYQ66/aOCtfyzHaXPLrRUPGfWkpM2K8BZAbduKRKl8TraYKXR77lZHOkWXsmVHQv9hroNgpDrJ5uqcH8J1XOT315Dy9qy1BhWD1reRWZ4Naw4OX3386MNe+upmF3yw3Aki3jH0bcnHfbIdPMWy4EokdMwtMXJIDa8l2xaV3woAZpuLvxb/SmQm+dBHFICtJS3RNxRfNwxOqggufBhXMGVPRIaQJF3Nhvx4zxCytySoIDAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQUXED6jDeuJb+aJC6jzTNbcutklzANBgkqhkiG9w0BAQsFAAOCAQEAS2QocQ4C/DocgyNOAN5bZCP/YcxL4F66aR94GW+2rzu5P5tf6qG4axmaJr3ZktNyYINY7Fx5apu/FeBh6vbHzUMqhKF6XfZr1m93lSXJ5pXIAU+0rmVpTPPLGnGDF4GYx36XR6cLaTo+IIKIC/vv+EukbsR0XZB5SvuEhdULn/Le+741P8Ja4imusUnA2TsLKWpwoc9fvYVkRY9CekRgh21XFLUzfoabJw9lGuK+xtqJ8H/tsoKR767/uQS3hlK75CY/2n/6sUGxehAFLMdNt4Zw9H+AIvOqANeNO8f/koAmI8tsKJRSKmjAWHGVCLT1F6w8dAX7DuRUVFvm81Dukg=="
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
