apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lvmetrics
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lvmetrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lvmetrics
    spec:
      containers:
        - name: lvmetrics
          image: lvmetrics:latest
          imagePullPolicy: Never
          command:
            - /lvmetrics
            - --socket=/tmp/lvmd.sock
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: empty-volume
            mountPath: /tmp
        - name: lvmd-fake
          image: lvmetrics:latest
          imagePullPolicy: Never
          command:
           - /lvmd
          volumeMounts:
          - name: empty-volume
            mountPath: /tmp
      volumes:
      - name: empty-volume
        emptyDir: {}
