apiVersion: apps/v1
kind: Deployment
metadata:
  name: topolvm-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-scheduler
    spec:
      containers:
        - name: topolvm-scheduler
          image: lvmetrics:latest
          imagePullPolicy: Never
          command:
            - /topolvm-scheduler
            - --listen=:8000
            - --divisor=1
            - --spare=1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: topolvm-scheduler
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: topolvm-scheduler
  type: ClusterIP
  clusterIP: 10.152.183.100
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: topolvm-scheduler-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "extenders" :
      [{
        "urlPrefix": "http://10.152.183.100/",
        "filterVerb": "predicate",
        "prioritizeVerb": "prioritize",
        "nodeCacheCapable": false,
        "weight": 1,
        "managedResources":
        [{
          "name": "topolvm.cybozu.com/capacity",
          "ignoredByScheduler": true
        }]
      }]
  }

