apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: topolvm-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-scheduler
    spec:
      containers:
        - name: topolvm-scheduler
          image: lvmetrics:latest
          imagePullPolicy: Never
          command:
            - /topolvm-scheduler
            - --listen=:9251
            - --divisor=1
            - --spare=1
          livenessProbe:
            httpGet:
              path: /status
              port: 9251
      hostNetwork: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: topolvm-scheduler-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "extenders" :
      [{
        "urlPrefix": "http://127.0.0.1:9251/",
        "filterVerb": "predicate",
        "prioritizeVerb": "prioritize",
        "nodeCacheCapable": false,
        "weight": 1,
        "managedResources":
        [{
          "name": "topolvm.cybozu.com/capacity",
          "ignoredByScheduler": true
        }]
      }]
  }

