apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topolvm-system
  name: topolvm-hook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topolvm-system:topolvm-hook
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topolvm-system:topolvm-hook
subjects:
  - kind: ServiceAccount
    name: topolvm-hook
    namespace: topolvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-system:topolvm-hook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topolvm-hook
  namespace: topolvm-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-hook
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-hook
    spec:
      serviceAccountName: topolvm-hook
      containers:
        - name: topolvm-hook
          image: topolvm:dev
          imagePullPolicy: Never
          command:
            - /topolvm-hook
            - --cert-dir=/certs
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
              scheme: HTTP
          volumeMounts:
            - name: server-certs
              mountPath: /certs
      volumes:
        - name: server-certs
          secret:
            secretName: topolvm-hook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: topolvm-hook
  namespace: topolvm-system
spec:
  selector:
    app.kubernetes.io/name: topolvm-hook
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
